-- 04_data_quality_checks.sql
-- Data quality checks for FACT_SALES

USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_AGENT_DB;
USE SCHEMA ANALYTICS;

-- 1) Null checks
SELECT
  SUM(IFF(ORDER_DATE IS NULL, 1, 0))  AS null_order_date,
  SUM(IFF(CUSTOMER_ID IS NULL, 1, 0)) AS null_customer_id,
  SUM(IFF(PRODUCT_ID IS NULL, 1, 0))  AS null_product_id,
  SUM(IFF(REGION_ID IS NULL, 1, 0))   AS null_region_id,
  SUM(IFF(QUANTITY IS NULL, 1, 0))    AS null_quantity,
  SUM(IFF(REVENUE IS NULL, 1, 0))     AS null_revenue
FROM FACT_SALES;

-- 2) Foreign key integrity checks
SELECT
  SUM(IFF(c.CUSTOMER_ID IS NULL, 1, 0)) AS bad_customer_fk,
  SUM(IFF(p.PRODUCT_ID IS NULL, 1, 0))  AS bad_product_fk,
  SUM(IFF(r.REGION_ID IS NULL, 1, 0))   AS bad_region_fk
FROM FACT_SALES f
LEFT JOIN DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN DIM_PRODUCT  p ON f.PRODUCT_ID  = p.PRODUCT_ID
LEFT JOIN DIM_REGION   r ON f.REGION_ID   = r.REGION_ID;

-- 3) Reusable DQ summary view
CREATE OR REPLACE VIEW V_DQ_FACT_SALES AS
SELECT 'NULL_ORDER_DATE' AS check_name, COUNT(*) AS failed_rows
FROM FACT_SALES WHERE ORDER_DATE IS NULL

UNION ALL
SELECT 'NULL_CUSTOMER_ID', COUNT(*)
FROM FACT_SALES WHERE CUSTOMER_ID IS NULL

UNION ALL
SELECT 'NULL_PRODUCT_ID', COUNT(*)
FROM FACT_SALES WHERE PRODUCT_ID IS NULL

UNION ALL
SELECT 'NULL_REGION_ID', COUNT(*)
FROM FACT_SALES WHERE REGION_ID IS NULL

UNION ALL
SELECT 'BAD_CUSTOMER_FK', COUNT(*)
FROM FACT_SALES f
LEFT JOIN DIM_CUSTOMER c
  ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL

UNION ALL
SELECT 'BAD_PRODUCT_FK', COUNT(*)
FROM FACT_SALES f
LEFT JOIN DIM_PRODUCT p
  ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL

UNION ALL
SELECT 'BAD_REGION_FK', COUNT(*)
FROM FACT_SALES f
LEFT JOIN DIM_REGION r
  ON f.REGION_ID = r.REGION_ID
WHERE r.REGION_ID IS NULL;

-- View usage
SELECT * FROM V_DQ_FACT_SALES ORDER BY failed_rows DESC;
